export enum CodeErrorEnum {
  PAGE_NOT_FOUND = "PAGE_NOT_FOUND",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  CATALOG_UNAVAILABLE = "CATALOG_UNAVAILABLE",
  CATALOG_NOT_FOUND = "CATALOG_NOT_FOUND",
  MALFORMED_PAYLOAD = "MALFORMED_PAYLOAD",
  OVERLAP = "OVERLAP",
  IDEMPOTENCY_KEY_REUSE = "IDEMPOTENCY_KEY_REUSE",
}
